### ISSUE TITLE
Update documentation: Building on MacBook M3 Architecture 

### ISSUE THREAD

**Issue by jcork-intel** [Thunder-Software-Technology-Malaysia/arcade-stem#7]
# Docker Build Architecture Issue on M3 MacBook Pro

## Problem

When deploying our Docker image to AWS Lambda from an M3 MacBook Pro, we encountered the following error:

```
RequestId: 94f4522c-3aff-4e91-aba4-126385666408 Error: fork/exec /lambda-entrypoint.sh: exec format error
Runtime.InvalidEntrypoint
```

This error occurred because the Docker image was built for the M3's ARM64 architecture by default, which is incompatible with AWS Lambda's x86_64 environment.

## Solution

To resolve this issue on an M3 MacBook Pro, we need to explicitly set the target platform to x86_64 when building the Docker image. Use the following command to build the image:

```bash
docker buildx build --platform linux/amd64 --no-cache -t artcade-api .
```

This command does the following:

1. Uses `docker buildx build` for multi-architecture support
2. Specifies the `linux/amd64` platform, which is compatible with AWS Lambda (instead of the M3's default ARM64)
3. Includes the `--no-cache` flag to ensure a fresh build
4. Tags the image as "artcade-api"
5. Uses the current directory (`.`) as the build context

**Comment by yeeyon** [comment]
it already resolved in the readme.
